Table admissions {
  subject_id int
  hadm_id int
  admittime timestamp
  dischtime timestamp
  deathtime timestamp
  admission_type varchar
  admit_provider_id varchar
  admission_location varchar
  discharge_location varchar
  insurance varchar
  language varchar
  marital_status varchar
  race varchar
  edregtime timestamp
  edouttime timestamp
  hospital_expire_flag int
}
Table d_hcpcs {
  code varchar
  category int
  long_description varchar
  short_description varchar
}
Table d_icd_diagnoses {
  icd_code varchar
  icd_version int
  long_title varchar
}
Table d_icd_procedures {
  icd_code varchar
  icd_version int
  long_title varchar
}
Table d_labitems {
  itemid int
  label varchar
  fluid varchar
  category varchar
}
Table diagnoses_icd {
  subject_id int
  hadm_id int
  seq_num int
  icd_code varchar
  icd_version int
}
Table drgcodes {
  subject_id int
  hadm_id int
  drg_type varchar
  drg_code varchar
  description varchar
  drg_severity int
  drg_mortality int
}
Table emar {
  subject_id int
  hadm_id int
  emar_id varchar
  emar_seq int
  poe_id varchar
  pharmacy_id int
  enter_provider_id varchar
  charttime timestamp
  medication varchar
  event_txt varchar
  scheduletime timestamp
  storetime timestamp
}
Table emar_detail {
  subject_id int
  emar_id varchar
  emar_seq int
  parent_field_ordinal double
  administration_type varchar
  pharmacy_id int
  barcode_type varchar
  reason_for_no_barcode varchar
  complete_dose_not_given varchar
  dose_due varchar
  dose_due_unit varchar
  dose_given varchar
  dose_given_unit varchar
  will_remainder_of_dose_be_given varchar
  product_amount_given double
  product_unit varchar
  product_code varchar
  product_description varchar
  product_description_other varchar
  prior_infusion_rate double
  infusion_rate double
  infusion_rate_adjustment varchar
  infusion_rate_adjustment_amount varchar
  infusion_rate_unit varchar
  route varchar
  infusion_complete varchar
  completion_interval varchar
  new_iv_bag_hung varchar
  continued_infusion_in_other_location varchar
  restart_interval varchar
  side varchar
  site varchar
  non_formulary_visual_verification varchar
}
Table hcpcsevents {
  subject_id int
  hadm_id int
  chartdate date
  hcpcs_cd varchar
  seq_num int
  short_description varchar
}
Table labevents {
  labevent_id int
  subject_id int
  hadm_id int
  specimen_id int
  itemid int
  order_provider_id varchar
  charttime timestamp
  storetime timestamp
  value varchar
  valuenum double
  valueuom varchar
  ref_range_lower double
  ref_range_upper double
  flag varchar
  priority varchar
  comments varchar
}
Table microbiologyevents {
  microevent_id int
  subject_id int
  hadm_id int
  micro_specimen_id int
  order_provider_id varchar
  chartdate timestamp
  charttime timestamp
  spec_itemid int
  spec_type_desc varchar
  test_seq int
  storedate timestamp
  storetime timestamp
  test_itemid int
  test_name varchar
  org_itemid int
  org_name varchar
  isolate_num int
  quantity varchar
  ab_itemid int
  ab_name varchar
  dilution_text varchar
  dilution_comparison varchar
  dilution_value double
  interpretation varchar
  comments varchar
}
Table omr {
  subject_id int
  chartdate date
  seq_num int
  result_name varchar
  result_value varchar
}
Table patients {
  subject_id int
  gender varchar
  anchor_age int
  anchor_year int
  anchor_year_group varchar
  dod date
}
Table pharmacy {
  subject_id int
  hadm_id int
  pharmacy_id int
  poe_id varchar
  starttime timestamp
  stoptime timestamp
  medication varchar
  proc_type varchar
  status varchar
  entertime timestamp
  verifiedtime timestamp
  route varchar
  frequency varchar
  disp_sched varchar
  infusion_type varchar
  sliding_scale varchar
  lockout_interval int
  basal_rate double
  one_hr_max double
  doses_per_24_hrs int
  duration int
  duration_interval varchar
  expiration_value int
  expiration_unit varchar
  expirationdate varchar
  dispensation varchar
  fill_quantity varchar
}
Table poe {
  poe_id varchar
  poe_seq int
  subject_id int
  hadm_id int
  ordertime timestamp
  order_type varchar
  order_subtype varchar
  transaction_type varchar
  discontinue_of_poe_id varchar
  discontinued_by_poe_id varchar
  order_provider_id varchar
  order_status varchar
}
Table poe_detail {
  poe_id varchar
  poe_seq int
  subject_id int
  field_name varchar
  field_value varchar
}
Table prescriptions {
  subject_id int
  hadm_id int
  pharmacy_id int
  poe_id varchar
  poe_seq int
  order_provider_id varchar
  starttime timestamp
  stoptime timestamp
  drug_type varchar
  drug varchar
  formulary_drug_cd varchar
  gsn varchar
  ndc varchar
  prod_strength varchar
  form_rx varchar
  dose_val_rx varchar
  dose_unit_rx varchar
  form_val_disp varchar
  form_unit_disp varchar
  doses_per_24_hrs int
  route varchar
}
Table procedures_icd {
  subject_id int
  hadm_id int
  seq_num int
  chartdate date
  icd_code varchar
  icd_version int
}
Table provider {
  provider_id varchar
}
Table services {
  subject_id int
  hadm_id int
  transfertime timestamp
  prev_service varchar
  curr_service varchar
}
Table transfers {
  subject_id int
  hadm_id int
  transfer_id int
  eventtype varchar
  careunit varchar
  intime timestamp
  outtime timestamp
}
