
Ref: admissions.subject_id > patients.subject_id
Ref: diagnoses_icd.subject_id > patients.subject_id
Ref: diagnoses_icd.hadm_id > admissions.hadm_id
Ref: diagnoses_icd.(icd_code, icd_version) > d_icd_diagnoses.(icd_code, icd_version)
Ref: procedures_icd.subject_id > patients.subject_id
Ref: procedures_icd.hadm_id > admissions.hadm_id
Ref: procedures_icd.(icd_code, icd_version) > d_icd_procedures.(icd_code, icd_version)
Ref: labevents.subject_id > patients.subject_id
Ref: labevents.itemid > d_labitems.itemid
Ref: transfers.subject_id > patients.subject_id
Ref: services.subject_id > patients.subject_id
Ref: services.hadm_id > admissions.hadm_id
Ref: drgcodes.subject_id > patients.subject_id
Ref: drgcodes.hadm_id > admissions.hadm_id
Ref: prescriptions.subject_id > patients.subject_id
Ref: prescriptions.hadm_id > admissions.hadm_id
Ref: pharmacy.subject_id > patients.subject_id
Ref: pharmacy.hadm_id > admissions.hadm_id
Ref: poe.subject_id > patients.subject_id
Ref: poe.hadm_id > admissions.hadm_id
Ref: hcpcsevents.subject_id > patients.subject_id
Ref: hcpcsevents.hadm_id > admissions.hadm_id
