-- 01_schema_inspection.sql
-- Performs basic schema inspection for the optional core-table workflow.
--
-- Purpose:
-- This script inspects the selected core tables loaded by 00_load_core_tables.sql.
-- It provides an initial check of loaded tables, row counts, column structures,
-- candidate identifiers, and selected relationships.
--
-- Note:
-- The main hospital-module table and column inventory is generated by
-- 07_export_hosp_identifier_inventory.sql after all hospital-module tables are
-- loaded using 05_load_all_hosp_tables.sql.

-- List loaded tables
SHOW TABLES FROM hosp;
SHOW TABLES FROM icu;

-- Row counts for selected core tables
SELECT 'hosp.patients' AS table_name, COUNT(*) AS row_count FROM hosp.patients
UNION ALL
SELECT 'hosp.admissions', COUNT(*) FROM hosp.admissions
UNION ALL
SELECT 'hosp.diagnoses_icd', COUNT(*) FROM hosp.diagnoses_icd
UNION ALL
SELECT 'hosp.d_icd_diagnoses', COUNT(*) FROM hosp.d_icd_diagnoses
UNION ALL
SELECT 'hosp.labevents', COUNT(*) FROM hosp.labevents
UNION ALL
SELECT 'hosp.d_labitems', COUNT(*) FROM hosp.d_labitems
UNION ALL
SELECT 'icu.icustays', COUNT(*) FROM icu.icustays;

-- Column inspection for selected core tables
DESCRIBE hosp.patients;
DESCRIBE hosp.admissions;
DESCRIBE hosp.diagnoses_icd;
DESCRIBE hosp.d_icd_diagnoses;
DESCRIBE hosp.labevents;
DESCRIBE hosp.d_labitems;
DESCRIBE icu.icustays;

-- Candidate identifier checks for selected core tables
-- These checks compare total row counts with distinct identifier values.
SELECT
    COUNT(*) AS rows,
    COUNT(DISTINCT subject_id) AS distinct_subject_id
FROM hosp.patients;

SELECT
    COUNT(*) AS rows,
    COUNT(DISTINCT subject_id) AS distinct_subject_id,
    COUNT(DISTINCT hadm_id) AS distinct_hadm_id
FROM hosp.admissions;

SELECT
    COUNT(*) AS rows,
    COUNT(DISTINCT stay_id) AS distinct_stay_id,
    COUNT(DISTINCT hadm_id) AS distinct_hadm_id,
    COUNT(DISTINCT subject_id) AS distinct_subject_id
FROM icu.icustays;

-- Selected relationship checks for the core-table workflow
-- These checks compare source rows with rows that match a proposed reference table.
SELECT
    COUNT(*) AS diagnosis_rows,
    COUNT(a.hadm_id) AS matched_to_admissions
FROM hosp.diagnoses_icd d
LEFT JOIN hosp.admissions a
    ON d.hadm_id = a.hadm_id;

SELECT
    COUNT(*) AS lab_rows,
    COUNT(a.hadm_id) AS matched_to_admissions
FROM hosp.labevents l
LEFT JOIN hosp.admissions a
    ON l.hadm_id = a.hadm_id;

SELECT
    COUNT(*) AS icu_stay_rows,
    COUNT(a.hadm_id) AS matched_to_admissions
FROM icu.icustays i
LEFT JOIN hosp.admissions a
    ON i.hadm_id = a.hadm_id;